language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m pytest tests/unit; fi
